const projects = [
    { id: '[ASDR]-001', title: '魇靥的第一封信——《你好》' },
    { id: '[ASDR]-002', title: '请细嚼慢咽' },
    { id: '[ASDR]-003', title: '梦想终点站' },
    { id: '[ASDR]-004', title: '星座之兽' },
    { id: '[ASDR]-005', title: '可恶的圣诞老人' },
    { id: '[ASDR]-006', title: '重击' },
    { id: '[ASDR]-007', title: '光的另一种函数哲理与认识' },
    { id: '[ASDR]-008', title: '“现实扭曲”的糖果' },
    { id: '[ASDR]-009', title: '冰晶' },
    { id: '[ASDR]-010', title: '死亡笔记' },
    { id: '[ASDR]-011', title: '智能乌贼' },
    { id: '[ASDR]-012', title: '心中阴影面积' },
    { id: '[ASDR]-013', title: '水晶球' },
    { id: '[ASDR]-014', title: '疯子' },
    { id: '[ASDR]-015', title: '泉水' },
    { id: '[ASDR]-016', title: '椅子' },
    { id: '[ASDR]-017', title: '丧尸鱼' },
    { id: '[ASDR]-018', title: '破碎的信念' },
    { id: '[ASDR]-019', title: '大人们' },
    { id: '[ASDR]-020', title: '塔上的一个洞' },
    { id: '[ASDR]-021', title: '巨毒蛛' },
    { id: '[ASDR]-022', title: '温水海洋中的巨蛇' },
    { id: '[ASDR]-023', title: '无处不在的花' },
    { id: '[ASDR]-024', title: '魇靥的第二封信——《它们》' },
    { id: '[ASDR]-025', title: '道德扭曲' },
    { id: '[ASDR]-026', title: '橡皮' },
    { id: '[ASDR]-027', title: '结构框架' },
    { id: '[ASDR]-028', title: '音符《朝日》' },
    { id: '[ASDR]-029', title: '地牢' },
    { id: '[ASDR]-030', title: '枪弹+电扇+收音机+电灯+■■(+微波炉+电冰箱+显示屏)' },
    { id: '[ASDR]-031', title: '你好!■■' },
    { id: '[ASDR]-032', title: '床下的人' },
    { id: '[ASDR]-033', title: '双面人' },
    { id: '[ASDR]-034', title: '“这好多了，真的，相信我!”' },
    { id: '[ASDR]-035', title: '宿伞诡' },
    { id: '[ASDR]-036', title: '钢笔蛇' },
    { id: '[ASDR]-037', title: '逝世闹钟' },
    { id: '[ASDR]-038', title: '模因磁带' },
    { id: '[ASDR]-039', title: '海中人型生物' },
    { id: '[ASDR]-040', title: '魇靥的第三封信——《死亡》' },
    { id: '[ASDR]-041', title: '人蛋' },
    { id: '[ASDR]-042', title: '次元垃圾箱' },
    { id: '[ASDR]-043', title: '阿托摩根之眼' },
    { id: '[ASDR]-044', title: 'Boy in the box' },
    { id: '[ASDR]-045', title: '骨胶原分子面膜' },
    { id: '[ASDR]-046', title: '口罩病' },
    { id: '[ASDR]-047', title: '死亡贩卖机' },
    { id: '[ASDR]-048', title: '宴会上的第七桌左边的那只不透明畸形玻璃酒杯' },
    { id: '[ASDR]-049', title: '异状蝴蝶' },
    { id: '[ASDR]-050', title: '黑暗中的启示' },
    { id: '[ASDR]-051', title: '克莱因瓶' },
    { id: '[ASDR]-052', title: '月球勇者' },
    { id: '[ASDR]-053', title: '火星液体' },
    { id: '[ASDR]-054', title: '8bit像素眼镜' },
    { id: '[ASDR]-055', title: '癌变星球' },
    { id: '[ASDR]-056', title: '园丁的后花园' },
    { id: '[ASDR]-057', title: '大雨' },
    { id: '[ASDR]-058', title: '“堵车”现象' },
    { id: '[ASDR]-059', title: '洪峰猛兽' },
    { id: '[ASDR]-060', title: '魇靥的第四封信——《忘记》' },
    { id: '[ASDR]-061', title: '蚊州' },
    { id: '[ASDR]-062', title: '梦乡与“它”' },
    { id: '[ASDR]-063', title: '德雷夫·难嘉克(机械废料)' },
    { id: '[ASDR]-064', title: '“臭虫”皮鞋' },
    { id: '[ASDR]-065', title: '必“中”彩票' },
    { id: '[ASDR]-066', title: '微型黑洞球拍' },
    { id: '[ASDR]-067', title: '异化柏树' },
    { id: '[ASDR]-068', title: '一幅山水画' },
    { id: '[ASDR]-069', title: '小包装式湿巾' },
    { id: '[ASDR]-070', title: '明信片' },
    { id: '[ASDR]-071', title: '“我记不住，先生”' },
    { id: '[ASDR]-072', title: '追溯链带' },
    { id: '[ASDR]-073', title: '点外卖' },
    { id: '[ASDR]-074', title: '女仆点心店' },
    { id: '[ASDR]-075', title: '涂鸦艺术' },
    { id: '[ASDR]-076', title: '脏乱的市区' },
    { id: '[ASDR]-077', title: '异空幻兽' },
    { id: '[ASDR]-078', title: '记忆空片' },
    { id: '[ASDR]-079', title: '心灵遮断合金窗' },
    { id: '[ASDR]-080', title: '一个笑话(really)' },
    { id: '[ASDR]-081', title: '智能互动实验' },
    { id: '[ASDR]-082', title: '黑板擦' },
    { id: '[ASDR]-083', title: '捆妖绳' },
    { id: '[ASDR]-084', title: '幻影森林' },
    { id: '[ASDR]-085', title: '家具游戏' },
    { id: '[ASDR]-086', title: '铸冻冰棍' },
    { id: '[ASDR]-087', title: '井口' },
    { id: '[ASDR]-088', title: '小鬼鼓队' },
    { id: '[ASDR]-089', title: '彼岸花河畔' },
    { id: '[ASDR]-090', title: '人皮文具袋' },
    { id: '[ASDR]-091', title: '小丑游乐场' },
    { id: '[ASDR]-092', title: '军火贩卖' },
    { id: '[ASDR]-093', title: '手掌病毒' },
    { id: '[ASDR]-094', title: '地球仪' },
    { id: '[ASDR]-095', title: '变性浴堂' },
    { id: '[ASDR]-096', title: '适应性活体心脏' },
    { id: '[ASDR]-097', title: '机械化试剂' },
    { id: '[ASDR]-098', title: '抹杀强制性精神物理污染源' },
    { id: '[ASDR]-099', title: '双人意识混合器' },
    { id: '[ASDR]-100', title: '雷神之锤' },
    { id: '[ASDR]-101', title: '一公斤的天空' },
    { id: '[ASDR]-102', title: '' },
    { id: '[ASDR]-103', title: '' },
    { id: '[ASDR]-104', title: '' },
    { id: '[ASDR]-105', title: '' },
    { id: '[ASDR]-106', title: '' },
    { id: '[ASDR]-107', title: '洇灭死光' },
    { id: '[ASDR]-108', title: '' },
    { id: '[ASDR]-109', title: '' },
    { id: '[ASDR]-110', title: '旧电视' },
    { id: '[ASDR]-111', title: '1:1万能打印机' },
    { id: '[ASDR]-112', title: '' },
    { id: '[ASDR]-113', title: '+' },
    { id: '[ASDR]-114', title: '' },
    { id: '[ASDR]-115', title: '' },
    { id: '[ASDR]-116', title: '' },
    { id: '[ASDR]-117', title: '梦发条' },
    { id: '[ASDR]-118', title: '' },
    { id: '[ASDR]-119', title: '' },
    { id: '[ASDR]-120', title: '' },
    { id: '[ASDR]-121', title: '魇靥的第五封信——《危机》' },
    { id: '[ASDR]-122', title: '' },
    { id: '[ASDR]-123', title: '' },
    { id: '[ASDR]-124', title: '莫比乌斯环窗帘带' },
    { id: '[ASDR]-125', title: '' },
    { id: '[ASDR]-126', title: '' },
    { id: '[ASDR]-127', title: '增值水宝宝' },
    { id: '[ASDR]-128', title: '水果碗' },
    { id: '[ASDR]-129', title: '' },
    { id: '[ASDR]-130', title: '卖身契' },
    { id: '[ASDR]-131', title: '' },
    { id: '[ASDR]-132', title: '' },
    { id: '[ASDR]-133', title: '磁胶' },
    { id: '[ASDR]-134', title: '' },
    { id: '[ASDR]-135', title: '变异鱼海域' },
    { id: '[ASDR]-136', title: '' },
    { id: '[ASDR]-137', title: '' },
    { id: '[ASDR]-138', title: '' },
    { id: '[ASDR]-139', title: '日本的樱花木刃' },
    { id: '[ASDR]-140', title: '' },
    { id: '[ASDR]-141', title: '' },
    { id: '[ASDR]-142', title: '特别的超市' },
    { id: '[ASDR]-143', title: '' },
    { id: '[ASDR]-144', title: '' },
    { id: '[ASDR]-145', title: '瘴气' },
    { id: '[ASDR]-146', title: '' },
    { id: '[ASDR]-147', title: '蠹虫毒菌' },
    { id: '[ASDR]-148', title: '人格分裂症' },
    { id: '[ASDR]-149', title: '重力控制器' },
    { id: '[ASDR]-150', title: '梦之假说' },
    { id: '[ASDR]-151', title: '' },
    { id: '[ASDR]-152', title: '' },
    { id: '[ASDR]-153', title: '“传染性”精神病' },
    { id: '[ASDR]-154', title: '红绳雾鬼' },
    { id: '[ASDR]-155', title: '' },
    { id: '[ASDR]-156', title: '' },
    { id: '[ASDR]-157', title: '' },
    { id: '[ASDR]-158', title: '' },
    { id: '[ASDR]-159', title: '' },
    { id: '[ASDR]-160', title: '' },
    { id: '[ASDR]-161', title: '随机诅咒生成器' },
    { id: '[ASDR]-162', title: '' },
    { id: '[ASDR]-163', title: '' },
    { id: '[ASDR]-164', title: '头发鬼' },
    { id: '[ASDR]-165', title: '' },
    { id: '[ASDR]-166', title: '' },
    { id: '[ASDR]-167', title: '' },
    { id: '[ASDR]-168', title: '自动会员' },
    { id: '[ASDR]-169', title: '' },
    { id: '[ASDR]-170', title: '魇靥的第六封信——《兴致》' },
    { id: '[ASDR]-171', title: '魔术师' },
    { id: '[ASDR]-172', title: '' },
    { id: '[ASDR]-173', title: '' },
    { id: '[ASDR]-174', title: '' },
    { id: '[ASDR]-175', title: '' },
    { id: '[ASDR]-176', title: '' },
    { id: '[ASDR]-177', title: '' },
    { id: '[ASDR]-178', title: '' },
    { id: '[ASDR]-179', title: '' },
    { id: '[ASDR]-180', title: '“1+1=11”' },
    { id: '[ASDR]-181', title: '' },
    { id: '[ASDR]-182', title: '' },
    { id: '[ASDR]-183', title: '' },
    { id: '[ASDR]-184', title: '空间扭曲水母' },
    { id: '[ASDR]-185', title: '客厅的大门' },
    { id: '[ASDR]-186', title: '生命即死' },
    { id: '[ASDR]-187', title: '' },
    { id: '[ASDR]-188', title: '超能力抽取表情包' },
    { id: '[ASDR]-189', title: '' },
    { id: '[ASDR]-190', title: '可怜的老头儿' },
    { id: '[ASDR]-191', title: '' },
    { id: '[ASDR]-192', title: '' },
    { id: '[ASDR]-193', title: '白色的黑书包' },
    { id: '[ASDR]-194', title: '' },
    { id: '[ASDR]-195', title: '' },
    { id: '[ASDR]-196', title: '' },
    { id: '[ASDR]-197', title: '' },
    { id: '[ASDR]-198', title: '' },
    { id: '[ASDR]-199', title: '矢' },
    { id: '[ASDR]-200', title: '入湖船桨' },
    { id: '[ASDR]-201', title: '剧中角色' },
    { id: '[ASDR]-202', title: '寻人寻物启事栏目' },
    { id: '[ASDR]-203', title: '缝纫机' },
    { id: '[ASDR]-204', title: '“积灰”理论' },
    { id: '[ASDR]-205', title: '文字狱' },
    { id: '[ASDR]-206', title: '永远海洋' },
    { id: '[ASDR]-207', title: '踊跃沙漏瓶' },
    { id: '[ASDR]-208', title: '迷性香火' },
    { id: '[ASDR]-209', title: '替死图腾' },
    { id: '[ASDR]-210', title: '失落雨伞' },
    { id: '[ASDR]-211', title: '垂泪藤' },
    { id: '[ASDR]-212', title: '灾火' },
    { id: '[ASDR]-213', title: '标本田' },
    { id: '[ASDR]-214', title: '魇靥的信箱' },
    { id: '[ASDR]-215', title: '水族馆' },
    { id: '[ASDR]-216', title: '悖论电梯' },
    { id: '[ASDR]-217', title: '葫芦藓' },
    { id: '[ASDR]-218', title: '雷魔' },
    { id: '[ASDR]-219', title: '圣诞颂歌副本手稿' },
    { id: '[ASDR]-220', title: '大气空间' },
    { id: '[ASDR]-221', title: '歪头男' },
    { id: '[ASDR]-222', title: '暴力词典' },
    { id: '[ASDR]-223', title: '水晶阵' },
    { id: '[ASDR]-224', title: '' },
    { id: '[ASDR]-225', title: '' },
    { id: '[ASDR]-226', title: '脑退化电话' },
    { id: '[ASDR]-227', title: '' },
    { id: '[ASDR]-228', title: '' },
    { id: '[ASDR]-229', title: '' },
    { id: '[ASDR]-230', title: '显灵旧钢琴' },
    { id: '[ASDR]-231', title: '' },
    { id: '[ASDR]-232', title: '' },
    { id: '[ASDR]-233', title: '' },
    { id: '[ASDR]-234', title: '孔雀舞' },
    { id: '[ASDR]-235', title: '' },
    { id: '[ASDR]-236', title: '' },
    { id: '[ASDR]-237', title: '' },
    { id: '[ASDR]-238', title: '' },
    { id: '[ASDR]-239', title: '魇靥的躯壳' },
    { id: '[ASDR]-240', title: '魇靥的第七封信——《罪恶》' },
    { id: '[ASDR]-241', title: '' },
    { id: '[ASDR]-242', title: '' },
    { id: '[ASDR]-243', title: '' },
    { id: '[ASDR]-244', title: '' },
    { id: '[ASDR]-245', title: '' },
    { id: '[ASDR]-246', title: '未知之地' },
    { id: '[ASDR]-247', title: '“吃人”草地' },
    { id: '[ASDR]-248', title: '胜利了！胜利了！' },
    { id: '[ASDR]-249', title: '杰克' },
    { id: '[ASDR]-250', title: '意外律' },
    { id: '[ASDR]-251', title: '火箭烟花' },
    { id: '[ASDR]-252', title: '鬼灵之医院' },
    { id: '[ASDR]-253', title: '人工智能' },
    { id: '[ASDR]-254', title: '蝶人花人' },
    { id: '[ASDR]-255', title: '' },
    { id: '[ASDR]-256', title: '布娃娃' },
    { id: '[ASDR]-257', title: '' },
    { id: '[ASDR]-258', title: '' },
    { id: '[ASDR]-259', title: '' },
    { id: '[ASDR]-260', title: '' },
    { id: '[ASDR]-261', title: '' },
    { id: '[ASDR]-262', title: '“唇亡齿寒”效应' },
    { id: '[ASDR]-263', title: '' },
    { id: '[ASDR]-264', title: '' },
    { id: '[ASDR]-265', title: '' },
    { id: '[ASDR]-266', title: '' },
    { id: '[ASDR]-267', title: '' },
    { id: '[ASDR]-268', title: '' },
    { id: '[ASDR]-269', title: '' },
    { id: '[ASDR]-270', title: '噩梦王冠' },
    { id: '[ASDR]-271', title: '“你完蛋了!”' },
    { id: '[ASDR]-272', title: '' },
    { id: '[ASDR]-273', title: '害怕结晶(一条绿黄瓜)' },
    { id: '[ASDR]-274', title: '' },
    { id: '[ASDR]-275', title: '' },
    { id: '[ASDR]-276', title: '' },
    { id: '[ASDR]-277', title: '' },
    { id: '[ASDR]-278', title: '' },
    { id: '[ASDR]-279', title: '大衣' },
    { id: '[ASDR]-280', title: '' },
    { id: '[ASDR]-281', title: '魇靥的第八封信——《梦境》' },
    { id: '[ASDR]-282', title: '' },
    { id: '[ASDR]-283', title: '' },
    { id: '[ASDR]-284', title: '' },
    { id: '[ASDR]-285', title: '' },
    { id: '[ASDR]-286', title: '' },
    { id: '[ASDR]-287', title: '████████████-██_███████-█' },
    { id: '[ASDR]-288', title: '悬飞羽' },
    { id: '[ASDR]-289', title: '' },
    { id: '[ASDR]-290', title: '灵异故事征集网' },
    { id: '[ASDR]-291', title: '' },
    { id: '[ASDR]-292', title: '' },
    { id: '[ASDR]-293', title: '' },
    { id: '[ASDR]-294', title: '' },
    { id: '[ASDR]-295', title: '' },
    { id: '[ASDR]-296', title: '' },
    { id: '[ASDR]-297', title: '' },
    { id: '[ASDR]-298', title: '' },
    { id: '[ASDR]-299', title: '杀人魔' },
    { id: '[ASDR]-300', title: '不可触摸' },
    { id: '[ASDR]-301', title: 'UFO不明飞行物' },
    { id: '[ASDR]-302', title: '' },
    { id: '[ASDR]-303', title: '现实VR眼镜' },
    { id: '[ASDR]-304', title: '龟甲占卜' },
    { id: '[ASDR]-305', title: '卡罗休克加亚斯' },
    { id: '[ASDR]-306', title: '楼上的低喃' },
    { id: '[ASDR]-307', title: '' },
    { id: '[ASDR]-308', title: '' },
    { id: '[ASDR]-309', title: '粉笔人' },
    { id: '[ASDR]-310', title: '' },
    { id: '[ASDR]-311', title: '完形填空' },
    { id: '[ASDR]-312', title: '' },
    { id: '[ASDR]-313', title: '' },
    { id: '[ASDR]-314', title: '' },
    { id: '[ASDR]-315', title: '' },
    { id: '[ASDR]-316', title: '不倒翁' },
    { id: '[ASDR]-317', title: '透明人病毒' },
    { id: '[ASDR]-318', title: '无限楼梯间' },
    { id: '[ASDR]-319', title: '' },
    { id: '[ASDR]-320', title: '' },
    { id: '[ASDR]-321', title: '因果律操作宝石(概念因果)' },
    { id: '[ASDR]-322', title: '葬花发髻' },
    { id: '[ASDR]-323', title: '你是谁？' },
    { id: '[ASDR]-324', title: '' },
    { id: '[ASDR]-325', title: '' },
    { id: '[ASDR]-326', title: '' },
    { id: '[ASDR]-327', title: '' },
    { id: '[ASDR]-328', title: '' },
    { id: '[ASDR]-329', title: '墣' },
    { id: '[ASDR]-330', title: '诡钥匙' },
    { id: '[ASDR]-331', title: '巨型毒蜈蚣' },
    { id: '[ASDR]-332', title: '美人鱼' },
    { id: '[ASDR]-333', title: '成为了画中人物' },
    { id: '[ASDR]-334', title: '' },
    { id: '[ASDR]-335', title: '诡血印记' },
    { id: '[ASDR]-336', title: '钟诡' },
    { id: '[ASDR]-337', title: '' },
    { id: '[ASDR]-338', title: '魇靥的第九封信——《宇宙》' },
    { id: '[ASDR]-339', title: '绝巘' },
    { id: '[ASDR]-340', title: '做不到的自行车' },
    { id: '[ASDR]-341', title: '' },
    { id: '[ASDR]-342', title: '' },
    { id: '[ASDR]-343', title: '' },
    { id: '[ASDR]-344', title: '' },
    { id: '[ASDR]-345', title: '' },
    { id: '[ASDR]-346', title: '骗人鬼' },
    { id: '[ASDR]-347', title: '' },
    { id: '[ASDR]-348', title: '最弱的盾' },
    { id: '[ASDR]-349', title: '' },
    { id: '[ASDR]-350', title: '肉山女皇' },
    { id: '[ASDR]-351', title: '' },
    { id: '[ASDR]-352', title: '' },
    { id: '[ASDR]-353', title: '' },
    { id: '[ASDR]-354', title: '' },
    { id: '[ASDR]-355', title: '重启性' },
    { id: '[ASDR]-356', title: '' },
    { id: '[ASDR]-357', title: '一年的第五个季节' },
    { id: '[ASDR]-358', title: '' },
    { id: '[ASDR]-359', title: '钻石兔雕' },
    { id: '[ASDR]-360', title: '魇靥的第十封信——《议会》' },
    { id: '[ASDR]-361', title: '吊死鬼' },
    { id: '[ASDR]-362', title: '禁脔' },
    { id: '[ASDR]-363', title: '' },
    { id: '[ASDR]-364', title: '' },
    { id: '[ASDR]-365', title: '' },
    { id: '[ASDR]-366', title: '' },
    { id: '[ASDR]-367', title: '纳米机器人' },
    { id: '[ASDR]-368', title: '打点播时器' },
    { id: '[ASDR]-369', title: '平行宇宙' },
    { id: '[ASDR]-370', title: '' },
    { id: '[ASDR]-371', title: '' },
    { id: '[ASDR]-372', title: '' },
    { id: '[ASDR]-373', title: '' },
    { id: '[ASDR]-374', title: '' },
    { id: '[ASDR]-375', title: '玛丽小姐的来电' },
    { id: '[ASDR]-376', title: '' },
    { id: '[ASDR]-377', title: '' },
    { id: '[ASDR]-378', title: '' },
    { id: '[ASDR]-379', title: '' },
    { id: '[ASDR]-380', title: '交易天平' },
    { id: '[ASDR]-381', title: '' },
    { id: '[ASDR]-382', title: '' },
    { id: '[ASDR]-383', title: '' },
    { id: '[ASDR]-384', title: '彩烁星' },
    { id: '[ASDR]-385', title: '拉链' },
    { id: '[ASDR]-386', title: '' },
    { id: '[ASDR]-387', title: '' },
    { id: '[ASDR]-388', title: '' },
    { id: '[ASDR]-389', title: '' },
    { id: '[ASDR]-390', title: '' },
    { id: '[ASDR]-391', title: '趱路人' },
    { id: '[ASDR]-392', title: '' },
    { id: '[ASDR]-393', title: '' },
    { id: '[ASDR]-394', title: '红鲷鱼' },
    { id: '[ASDR]-395', title: '' },
    { id: '[ASDR]-396', title: '' },
    { id: '[ASDR]-397', title: '' },
    { id: '[ASDR]-398', title: '' },
    { id: '[ASDR]-399', title: '定风波' },
    { id: '[ASDR]-400', title: '盖帽笔' },
    { id: '[ASDR]-401', title: '' },
    { id: '[ASDR]-402', title: '' },
    { id: '[ASDR]-403', title: '' },
    { id: '[ASDR]-404', title: '' },
    { id: '[ASDR]-405', title: '' },
    { id: '[ASDR]-406', title: '' },
    { id: '[ASDR]-407', title: '' },
    { id: '[ASDR]-408', title: '雨点讲坛' },
    { id: '[ASDR]-409', title: '' },
    { id: '[ASDR]-410', title: '粉碎机' },
    { id: '[ASDR]-411', title: '' },
    { id: '[ASDR]-412', title: '' },
    { id: '[ASDR]-413', title: '' },
    { id: '[ASDR]-414', title: '异常台阶' },
    { id: '[ASDR]-415', title: '' },
    { id: '[ASDR]-416', title: '' },
    { id: '[ASDR]-417', title: '莫名其妙混沌规则' },
    { id: '[ASDR]-418', title: '' },
    { id: '[ASDR]-419', title: '结构失效者' },
    { id: '[ASDR]-420', title: '潜意识暗示便签' },
    { id: '[ASDR]-421', title: '' },
    { id: '[ASDR]-422', title: '' },
    { id: '[ASDR]-423', title: '' },
    { id: '[ASDR]-424', title: '' },
    { id: '[ASDR]-425', title: '绝对一石二鸟弹弓' },
    { id: '[ASDR]-426', title: '' },
    { id: '[ASDR]-427', title: '' },
    { id: '[ASDR]-428', title: '' },
    { id: '[ASDR]-429', title: '' },
    { id: '[ASDR]-430', title: '占卜传承' },
    { id: '[ASDR]-431', title: '空心矿界' },
    { id: '[ASDR]-432', title: '' },
    { id: '[ASDR]-433', title: '神医娃娃' },
    { id: '[ASDR]-434', title: '元素白漆' },
    { id: '[ASDR]-435', title: '' },
    { id: '[ASDR]-436', title: '随破晓轮滑' },
    { id: '[ASDR]-437', title: '' },
    { id: '[ASDR]-438', title: '' },
    { id: '[ASDR]-439', title: '' },
    { id: '[ASDR]-440', title: '超然立场控制仪' },
    { id: '[ASDR]-441', title: '' },
    { id: '[ASDR]-442', title: '' },
    { id: '[ASDR]-443', title: '' },
    { id: '[ASDR]-444', title: '' },
    { id: '[ASDR]-445', title: '圆滑线或是延音线' },
    { id: '[ASDR]-446', title: '' },
    { id: '[ASDR]-447', title: '' },
    { id: '[ASDR]-448', title: '' },
    { id: '[ASDR]-449', title: '' },
    { id: '[ASDR]-450', title: '沉浸式互动视频(《△绝命!这绝对是你前所未见的!第一视角沉浸式体验被山羊追逐!😱(4K高帧率纯享)》)' },
    { id: '[ASDR]-451', title: '爱心' },
    { id: '[ASDR]-452', title: '' },
    { id: '[ASDR]-453', title: '' },
    { id: '[ASDR]-454', title: '' },
    { id: '[ASDR]-455', title: '' },
    { id: '[ASDR]-456', title: '' },
    { id: '[ASDR]-457', title: '' },
    { id: '[ASDR]-458', title: '亚人类' },
    { id: '[ASDR]-459', title: '' },
    { id: '[ASDR]-460', title: '' },
    { id: '[ASDR]-461', title: '' },
    { id: '[ASDR]-462', title: '' },
    { id: '[ASDR]-463', title: '' },
    { id: '[ASDR]-464', title: '幽灵空调' },
    { id: '[ASDR]-465', title: '伪装梯' },
    { id: '[ASDR]-466', title: '' },
    { id: '[ASDR]-467', title: '' },
    { id: '[ASDR]-468', title: '' },
    { id: '[ASDR]-469', title: '九骷' },
    { id: '[ASDR]-470', title: '' },
    { id: '[ASDR]-471', title: '隔画取物' },
    { id: '[ASDR]-472', title: '' },
    { id: '[ASDR]-473', title: '' },
    { id: '[ASDR]-474', title: '' },
    { id: '[ASDR]-475', title: '燃用纸飞机' },
    { id: '[ASDR]-476', title: '' },
    { id: '[ASDR]-477', title: '' },
    { id: '[ASDR]-478', title: '' },
    { id: '[ASDR]-479', title: '' },
    { id: '[ASDR]-480', title: '队歌集伍效应' },
    { id: '[ASDR]-481', title: '' },
    { id: '[ASDR]-482', title: '披靡防晒衣' },
    { id: '[ASDR]-483', title: '' },
    { id: '[ASDR]-484', title: '' },
    { id: '[ASDR]-485', title: '' },
    { id: '[ASDR]-486', title: '' },
    { id: '[ASDR]-487', title: '' },
    { id: '[ASDR]-488', title: '加工微波炉' },
    { id: '[ASDR]-489', title: '' },
    { id: '[ASDR]-490', title: '夜巡航班' },
    { id: '[ASDR]-491', title: 'KK级末日' },
    { id: '[ASDR]-492', title: '' },
    { id: '[ASDR]-493', title: '' },
    { id: '[ASDR]-494', title: '噬血钢笔' },
    { id: '[ASDR]-495', title: '' },
    { id: '[ASDR]-496', title: '' },
    { id: '[ASDR]-497', title: '' },
    { id: '[ASDR]-498', title: '' },
    { id: '[ASDR]-499', title: '赋职' },
    { id: '[ASDR]-500', title: '妄想哀歌' },
    { id: '[ASDR]-501', title: '“请不要掠夺我的记忆”' },
    { id: '[ASDR]-502', title: '牙模因' },
    { id: '[ASDR]-503', title: '' },
    { id: '[ASDR]-504', title: '' },
    { id: '[ASDR]-505', title: '' },
    { id: '[ASDR]-506', title: '' },
    { id: '[ASDR]-507', title: '' },
    { id: '[ASDR]-508', title: '' },
    { id: '[ASDR]-509', title: '蓝蝎子手枪' },
    { id: '[ASDR]-510', title: '升级金币' },
    { id: '[ASDR]-511', title: '规则棋局游戏' },
    { id: '[ASDR]-512', title: '灵感漏斗' },
    { id: '[ASDR]-513', title: '' },
    { id: '[ASDR]-514', title: '' },
    { id: '[ASDR]-515', title: '' },
    { id: '[ASDR]-516', title: '' },
    { id: '[ASDR]-517', title: '动态化石群' },
    { id: '[ASDR]-518', title: '' },
    { id: '[ASDR]-519', title: '' },
    { id: '[ASDR]-520', title: '“她”' },
    { id: '[ASDR]-521', title: '' },
    { id: '[ASDR]-522', title: '' },
    { id: '[ASDR]-523', title: '即兴发挥' },
    { id: '[ASDR]-524', title: '午餐板' },
    { id: '[ASDR]-525', title: '' },
    { id: '[ASDR]-526', title: '' },
    { id: '[ASDR]-527', title: '' },
    { id: '[ASDR]-528', title: '' },
    { id: '[ASDR]-529', title: '' },
    { id: '[ASDR]-530', title: '' },
    { id: '[ASDR]-531', title: '电缘手套' },
    { id: '[ASDR]-532', title: '' },
    { id: '[ASDR]-533', title: '(根本不存在的)达摩克利斯之剑' },
    { id: '[ASDR]-534', title: '' },
    { id: '[ASDR]-535', title: '' },
    { id: '[ASDR]-536', title: '' },
    { id: '[ASDR]-537', title: '' },
    { id: '[ASDR]-538', title: '' },
    { id: '[ASDR]-539', title: '' },
    { id: '[ASDR]-540', title: '浮沉珠' },
    { id: '[ASDR]-541', title: '' },
    { id: '[ASDR]-542', title: '雪女' },
    { id: '[ASDR]-543', title: '' },
    { id: '[ASDR]-544', title: '关系证明书' },
    { id: '[ASDR]-545', title: '' },
    { id: '[ASDR]-546', title: '' },
    { id: '[ASDR]-547', title: '' },
    { id: '[ASDR]-548', title: '' },
    { id: '[ASDR]-549', title: '断更账号' },
    { id: '[ASDR]-550', title: '跨过去商品交易商店小站' },
    { id: '[ASDR]-551', title: '' },
    { id: '[ASDR]-552', title: '' },
    { id: '[ASDR]-553', title: '' },
    { id: '[ASDR]-554', title: '' },
    { id: '[ASDR]-555', title: '' },
    { id: '[ASDR]-556', title: '野人族' },
    { id: '[ASDR]-557', title: '' },
    { id: '[ASDR]-558', title: '' },
    { id: '[ASDR]-559', title: '' },
    { id: '[ASDR]-560', title: '' },
    { id: '[ASDR]-561', title: '' },
    { id: '[ASDR]-562', title: '' },
    { id: '[ASDR]-563', title: '' },
    { id: '[ASDR]-564', title: '穿越故事的量尺' },
    { id: '[ASDR]-565', title: '' },
    { id: '[ASDR]-566', title: '无限零食袋' },
    { id: '[ASDR]-567', title: '' },
    { id: '[ASDR]-568', title: '' },
    { id: '[ASDR]-569', title: '' },
    { id: '[ASDR]-570', title: '将军的武库' },
    { id: '[ASDR]-571', title: '' },
    { id: '[ASDR]-572', title: '' },
    { id: '[ASDR]-573', title: '梦语都市' },
    { id: '[ASDR]-574', title: '' },
    { id: '[ASDR]-575', title: '无解破伤风' },
    { id: '[ASDR]-576', title: '' },
    { id: '[ASDR]-577', title: '' },
    { id: '[ASDR]-578', title: '' },
    { id: '[ASDR]-579', title: '' },
    { id: '[ASDR]-580', title: '女友机器人' },
    { id: '[ASDR]-581', title: '' },
    { id: '[ASDR]-582', title: '' },
    { id: '[ASDR]-583', title: '' },
    { id: '[ASDR]-584', title: '' },
    { id: '[ASDR]-585', title: '' },
    { id: '[ASDR]-586', title: '食人花' },
    { id: '[ASDR]-587', title: '' },
    { id: '[ASDR]-588', title: '' },
    { id: '[ASDR]-589', title: '' },
    { id: '[ASDR]-590', title: '' },
    { id: '[ASDR]-591', title: '' },
    { id: '[ASDR]-592', title: '' },
    { id: '[ASDR]-593', title: '' },
    { id: '[ASDR]-594', title: '后颈有水' },
    { id: '[ASDR]-595', title: '' },
    { id: '[ASDR]-596', title: '' },
    { id: '[ASDR]-597', title: '' },
    { id: '[ASDR]-598', title: '' },
    { id: '[ASDR]-599', title: '破阵子' },
    { id: '[ASDR]-600', title: '太空巨鲸' },
    { id: '[ASDR]-601', title: '' },
    { id: '[ASDR]-602', title: '' },
    { id: '[ASDR]-603', title: '' },
    { id: '[ASDR]-604', title: '' },
    { id: '[ASDR]-605', title: '' },
    { id: '[ASDR]-606', title: '不会亮的电灯' },
    { id: '[ASDR]-607', title: '' },
    { id: '[ASDR]-608', title: '' },
    { id: '[ASDR]-609', title: '点指冰冰' },
    { id: '[ASDR]-610', title: '香水' },
    { id: '[ASDR]-611', title: '' },
    { id: '[ASDR]-612', title: '' },
    { id: '[ASDR]-613', title: '不存在的好友' },
    { id: '[ASDR]-614', title: '' },
    { id: '[ASDR]-615', title: '' },
    { id: '[ASDR]-616', title: '暖风循环' },
    { id: '[ASDR]-617', title: '' },
    { id: '[ASDR]-618', title: '' },
    { id: '[ASDR]-619', title: '' },
    { id: '[ASDR]-620', title: '风铃' },
    { id: '[ASDR]-621', title: '' },
    { id: '[ASDR]-622', title: '' },
    { id: '[ASDR]-623', title: '' },
    { id: '[ASDR]-624', title: '阿斯特拉空调遥控器' },
    { id: '[ASDR]-625', title: '' },
    { id: '[ASDR]-626', title: '' },
    { id: '[ASDR]-627', title: '' },
    { id: '[ASDR]-628', title: '' },
    { id: '[ASDR]-629', title: '' },
    { id: '[ASDR]-630', title: '拉普拉斯之妖' },
    { id: '[ASDR]-631', title: '入肉蠕虫' },
    { id: '[ASDR]-632', title: '' },
    { id: '[ASDR]-633', title: '宝藏洛阳铲' },
    { id: '[ASDR]-634', title: '' },
    { id: '[ASDR]-635', title: '' },
    { id: '[ASDR]-636', title: '' },
    { id: '[ASDR]-637', title: '' },
    { id: '[ASDR]-638', title: '' },
    { id: '[ASDR]-639', title: '' },
    { id: '[ASDR]-640', title: '' },
    { id: '[ASDR]-641', title: '' },
    { id: '[ASDR]-642', title: '宇宙内模拟用超级计算机' },
    { id: '[ASDR]-643', title: '' },
    { id: '[ASDR]-644', title: '' },
    { id: '[ASDR]-645', title: '' },
    { id: '[ASDR]-646', title: '' },
    { id: '[ASDR]-647', title: '' },
    { id: '[ASDR]-648', title: '' },
    { id: '[ASDR]-649', title: '' },
    { id: '[ASDR]-650', title: '网线支持开户' },
    { id: '[ASDR]-651', title: '' },
    { id: '[ASDR]-652', title: '' },
    { id: '[ASDR]-653', title: '幻景重演盒' },
    { id: '[ASDR]-654', title: '' },
    { id: '[ASDR]-655', title: '' },
    { id: '[ASDR]-656', title: '腐铁' },
    { id: '[ASDR]-657', title: '睡衣帽' },
    { id: '[ASDR]-658', title: '' },
    { id: '[ASDR]-659', title: '耳边之歌' },
    { id: '[ASDR]-660', title: '魇靥的第十一封信——《回归》' },
    { id: '[ASDR]-661', title: '' },
    { id: '[ASDR]-662', title: '' },
    { id: '[ASDR]-663', title: '' },
    { id: '[ASDR]-664', title: '' },
    { id: '[ASDR]-665', title: '' },
    { id: '[ASDR]-666', title: '17480963384112……+' },
    { id: '[ASDR]-667', title: '' },
    { id: '[ASDR]-668', title: '' },
    { id: '[ASDR]-669', title: '灵异对撞机' },
    { id: '[ASDR]-670', title: '' },
    { id: '[ASDR]-671', title: '' },
    { id: '[ASDR]-672', title: '反面羽毛支教' },
    { id: '[ASDR]-673', title: '' },
    { id: '[ASDR]-674', title: '' },
    { id: '[ASDR]-675', title: '' },
    { id: '[ASDR]-676', title: '' },
    { id: '[ASDR]-677', title: '千人扇' },
    { id: '[ASDR]-678', title: '' },
    { id: '[ASDR]-679', title: '' },
    { id: '[ASDR]-680', title: '致不被列入终幕表的' },
    { id: '[ASDR]-681', title: '' },
    { id: '[ASDR]-682', title: '' },
    { id: '[ASDR]-683', title: '' },
    { id: '[ASDR]-684', title: '扭蛋机' },
    { id: '[ASDR]-685', title: '坠落的空气' },
    { id: '[ASDR]-686', title: '' },
    { id: '[ASDR]-687', title: '' },
    { id: '[ASDR]-688', title: '自由变化门牌' },
    { id: '[ASDR]-689', title: '' },
    { id: '[ASDR]-690', title: '异变银星' },
    { id: '[ASDR]-691', title: '镜面后的世界' },
    { id: '[ASDR]-692', title: '活体大气' },
    { id: '[ASDR]-693', title: '第十三名' },
    { id: '[ASDR]-694', title: '' },
    { id: '[ASDR]-695', title: '' },
    { id: '[ASDR]-696', title: '灭绝' },
    { id: '[ASDR]-697', title: '复蛇灵' },
    { id: '[ASDR]-698', title: '' },
    { id: '[ASDR]-699', title: '厄运宝石' },
    { id: '[ASDR]-700', title: '不辨经' },
    { id: '[ASDR]-701', title: '孩子们的贴纸' },
    { id: '[ASDR]-702', title: '' },
    { id: '[ASDR]-703', title: '孤独者投影' },
    { id: '[ASDR]-704', title: '' },
    { id: '[ASDR]-705', title: '' },
    { id: '[ASDR]-706', title: '' },
    { id: '[ASDR]-707', title: '' },
    { id: '[ASDR]-708', title: '' },
    { id: '[ASDR]-709', title: '拟人雕像' },
    { id: '[ASDR]-710', title: '' },
    { id: '[ASDR]-711', title: '' },
    { id: '[ASDR]-712', title: '' },
    { id: '[ASDR]-713', title: '真相模因报刊栏目《真相之窗（Window to Truth）》' },
    { id: '[ASDR]-714', title: '' },
    { id: '[ASDR]-715', title: '' },
    { id: '[ASDR]-716', title: '' },
    { id: '[ASDR]-717', title: '' },
    { id: '[ASDR]-718', title: '' },
    { id: '[ASDR]-719', title: '生命大爆发' },
    { id: '[ASDR]-720', title: '' },
    { id: '[ASDR]-721', title: '沾血的正十字架' },
    { id: '[ASDR]-722', title: '圣洁的倒十字架' },
    { id: '[ASDR]-723', title: '' },
    { id: '[ASDR]-724', title: '' },
    { id: '[ASDR]-725', title: '水压蝠鲼' },
    { id: '[ASDR]-726', title: '' },
    { id: '[ASDR]-727', title: '' },
    { id: '[ASDR]-728', title: '' },
    { id: '[ASDR]-729', title: '' },
    { id: '[ASDR]-730', title: '因果调试棒(物理因果)' },
    { id: '[ASDR]-731', title: '' },
    { id: '[ASDR]-732', title: '' },
    { id: '[ASDR]-733', title: '' },
    { id: '[ASDR]-734', title: '' },
    { id: '[ASDR]-735', title: '人相熊' },
    { id: '[ASDR]-736', title: '' },
    { id: '[ASDR]-737', title: '' },
    { id: '[ASDR]-738', title: '' },
    { id: '[ASDR]-739', title: '' },
    { id: '[ASDR]-740', title: '海报' },
    { id: '[ASDR]-741', title: '翡翠香梨' },
    { id: '[ASDR]-742', title: '' },
    { id: '[ASDR]-743', title: '' },
    { id: '[ASDR]-744', title: '' },
    { id: '[ASDR]-745', title: '' },
    { id: '[ASDR]-746', title: '' },
    { id: '[ASDR]-747', title: '' },
    { id: '[ASDR]-748', title: '' },
    { id: '[ASDR]-749', title: '捕捉生物摄像机' },
    { id: '[ASDR]-750', title: '钓星星' },
    { id: '[ASDR]-751', title: '' },
    { id: '[ASDR]-752', title: '' },
    { id: '[ASDR]-753', title: '' },
    { id: '[ASDR]-754', title: '魇靥的第十二封信——《海星》' },
    { id: '[ASDR]-755', title: '' },
    { id: '[ASDR]-756', title: '查阅段位的游戏账户' },
    { id: '[ASDR]-757', title: '' },
    { id: '[ASDR]-758', title: '' },
    { id: '[ASDR]-759', title: '数字三与四之间的整数' },
    { id: '[ASDR]-760', title: '' },
    { id: '[ASDR]-761', title: '' },
    { id: '[ASDR]-762', title: '' },
    { id: '[ASDR]-763', title: '' },
    { id: '[ASDR]-764', title: '最佳名选' },
    { id: '[ASDR]-765', title: '' },
    { id: '[ASDR]-766', title: '' },
    { id: '[ASDR]-767', title: '' },
    { id: '[ASDR]-768', title: '' },
    { id: '[ASDR]-769', title: '' },
    { id: '[ASDR]-770', title: '' },
    { id: '[ASDR]-771', title: '' },
    { id: '[ASDR]-772', title: '鬼来电' },
    { id: '[ASDR]-773', title: '' },
    { id: '[ASDR]-774', title: '' },
    { id: '[ASDR]-775', title: '' },
    { id: '[ASDR]-776', title: '恐龙人' },
    { id: '[ASDR]-777', title: '消失现实分子重构光线枪' },
    { id: '[ASDR]-778', title: '' },
    { id: '[ASDR]-779', title: '' },
    { id: '[ASDR]-780', title: '鬼桃源' },
    { id: '[ASDR]-781', title: '' },
    { id: '[ASDR]-782', title: '' },
    { id: '[ASDR]-783', title: '' },
    { id: '[ASDR]-784', title: '' },
    { id: '[ASDR]-785', title: '' },
    { id: '[ASDR]-786', title: '润滑剂' },
    { id: '[ASDR]-787', title: '石头人病毒' },
    { id: '[ASDR]-788', title: '' },
    { id: '[ASDR]-789', title: '' },
    { id: '[ASDR]-790', title: '' },
    { id: '[ASDR]-791', title: '' },
    { id: '[ASDR]-792', title: '' },
    { id: '[ASDR]-793', title: '' },
    { id: '[ASDR]-794', title: '' },
    { id: '[ASDR]-795', title: '' },
    { id: '[ASDR]-796', title: '' },
    { id: '[ASDR]-797', title: '电子眼球' },
    { id: '[ASDR]-798', title: '' },
    { id: '[ASDR]-799', title: '人体急性脱水毒素' },
    { id: '[ASDR]-800', title: '四足珊瑚鱼' },
    { id: '[ASDR]-801', title: '认知二向箔' },
    { id: '[ASDR]-802', title: '' },
    { id: '[ASDR]-803', title: '' },
    { id: '[ASDR]-804', title: '' },
    { id: '[ASDR]-805', title: '' },
    { id: '[ASDR]-806', title: '死亡之梦' },
    { id: '[ASDR]-807', title: '喷射子弹的三色堇' },
    { id: '[ASDR]-808', title: '' },
    { id: '[ASDR]-809', title: '' },
    { id: '[ASDR]-810', title: '' },
    { id: '[ASDR]-811', title: '魇靥的第十三封信——《洪水》' },
    { id: '[ASDR]-812', title: '火焰树' },
    { id: '[ASDR]-813', title: '' },
    { id: '[ASDR]-814', title: '' },
    { id: '[ASDR]-815', title: '数据库/信息箱/资讯场/资料集' },
    { id: '[ASDR]-816', title: '' },
    { id: '[ASDR]-817', title: '' },
    { id: '[ASDR]-818', title: '' },
    { id: '[ASDR]-819', title: '' },
    { id: '[ASDR]-820', title: '' },
    { id: '[ASDR]-821', title: '退化分子激光枪' },
    { id: '[ASDR]-822', title: '' },
    { id: '[ASDR]-823', title: '窟窿' },
    { id: '[ASDR]-824', title: '' },
    { id: '[ASDR]-825', title: '花开满了世界的洞天' },
    { id: '[ASDR]-826', title: '' },
    { id: '[ASDR]-827', title: '' },
    { id: '[ASDR]-828', title: '' },
    { id: '[ASDR]-829', title: '' },
    { id: '[ASDR]-830', title: '' },
    { id: '[ASDR]-831', title: '' },
    { id: '[ASDR]-832', title: '' },
    { id: '[ASDR]-833', title: '相反剃须刀' },
    { id: '[ASDR]-834', title: '' },
    { id: '[ASDR]-835', title: '' },
    { id: '[ASDR]-836', title: '断头台' },
    { id: '[ASDR]-837', title: '' },
    { id: '[ASDR]-838', title: '' },
    { id: '[ASDR]-839', title: '' },
    { id: '[ASDR]-840', title: '' },
    { id: '[ASDR]-841', title: '“不可言说”的生物组织团' },
    { id: '[ASDR]-842', title: '' },
    { id: '[ASDR]-843', title: '第三人称单数' },
    { id: '[ASDR]-844', title: '' },
    { id: '[ASDR]-845', title: '' },
    { id: '[ASDR]-846', title: '' },
    { id: '[ASDR]-847', title: '' },
    { id: '[ASDR]-848', title: '' },
    { id: '[ASDR]-849', title: '' },
    { id: '[ASDR]-850', title: '蜡笔盒' },
    { id: '[ASDR]-851', title: '' },
    { id: '[ASDR]-852', title: '高温台灯' },
    { id: '[ASDR]-853', title: '' },
    { id: '[ASDR]-854', title: '机动鲨鱼' },
    { id: '[ASDR]-855', title: '' },
    { id: '[ASDR]-856', title: '' },
    { id: '[ASDR]-857', title: '' },
    { id: '[ASDR]-858', title: '' },
    { id: '[ASDR]-859', title: '魔高一丈' },
    { id: '[ASDR]-860', title: '死人车' },
    { id: '[ASDR]-861', title: '紫城宫' },
    { id: '[ASDR]-862', title: '' },
    { id: '[ASDR]-863', title: '' },
    { id: '[ASDR]-864', title: '' },
    { id: '[ASDR]-865', title: '' },
    { id: '[ASDR]-866', title: 'WAT' },
    { id: '[ASDR]-867', title: '被全世界禁养的猫' },
    { id: '[ASDR]-868', title: '猎鹰K-14' },
    { id: '[ASDR]-869', title: '心灵历史' },
    { id: '[ASDR]-870', title: '那轰然一声巨响' },
    { id: '[ASDR]-871', title: '美食性核射天体' },
    { id: '[ASDR]-872', title: '我们也是星尘' },
    { id: '[ASDR]-873', title: '最巧妙的玩具——积木' },
    { id: '[ASDR]-874', title: '命运齿轮' },
    { id: '[ASDR]-875', title: '没有一件事物来自空无' },
    { id: '[ASDR]-876', title: '柏拉图' },
    { id: '[ASDR]-877', title: '魇靥的第十四封信——《神话》' },
    { id: '[ASDR]-878', title: '不朽的灵魂' },
    { id: '[ASDR]-879', title: '迷失之齿' },
    { id: '[ASDR]-880', title: '吞噬巨兽-拉格迦斯' },
    { id: '[ASDR]-881', title: '' },
    { id: '[ASDR]-882', title: '' },
    { id: '[ASDR]-883', title: '' },
    { id: '[ASDR]-884', title: '' },
    { id: '[ASDR]-885', title: '' },
    { id: '[ASDR]-886', title: '' },
    { id: '[ASDR]-887', title: '' },
    { id: '[ASDR]-888', title: '财神爷' },
    { id: '[ASDR]-889', title: '凤鸟' },
    { id: '[ASDR]-890', title: '' },
    { id: '[ASDR]-891', title: '' },
    { id: '[ASDR]-892', title: '' },
    { id: '[ASDR]-893', title: '' },
    { id: '[ASDR]-894', title: '品红顾问' },
    { id: '[ASDR]-895', title: '苍蝇与战士' },
    { id: '[ASDR]-896', title: '星体天座星象图' },
    { id: '[ASDR]-897', title: '心灵匣子' },
    { id: '[ASDR]-898', title: '' },
    { id: '[ASDR]-899', title: '“神”' },
    { id: '[ASDR]-900', title: '水泵' },
    { id: '[ASDR]-901', title: '囚诡' },
    { id: '[ASDR]-902', title: '' },
    { id: '[ASDR]-903', title: '' },
    { id: '[ASDR]-904', title: '' },
    { id: '[ASDR]-905', title: '' },
    { id: '[ASDR]-906', title: '' },
    { id: '[ASDR]-907', title: '' },
    { id: '[ASDR]-908', title: '' },
    { id: '[ASDR]-909', title: '' },
    { id: '[ASDR]-910', title: '无双之剑' },
    { id: '[ASDR]-911', title: '' },
    { id: '[ASDR]-912', title: '' },
    { id: '[ASDR]-913', title: '' },
    { id: '[ASDR]-914', title: '' },
    { id: '[ASDR]-915', title: '工厂' },
    { id: '[ASDR]-916', title: '' },
    { id: '[ASDR]-917', title: '' },
    { id: '[ASDR]-918', title: '' },
    { id: '[ASDR]-919', title: '' },
    { id: '[ASDR]-920', title: '图书馆' },
    { id: '[ASDR]-921', title: '' },
    { id: '[ASDR]-922', title: '' },
    { id: '[ASDR]-923', title: '' },
    { id: '[ASDR]-924', title: '' },
    { id: '[ASDR]-925', title: '房奴' },
    { id: '[ASDR]-926', title: '' },
    { id: '[ASDR]-927', title: '' },
    { id: '[ASDR]-928', title: '' },
    { id: '[ASDR]-929', title: '' },
    { id: '[ASDR]-930', title: '' },
    { id: '[ASDR]-931', title: '' },
    { id: '[ASDR]-932', title: '' },
    { id: '[ASDR]-933', title: '鬼学校' },
    { id: '[ASDR]-934', title: '' },
    { id: '[ASDR]-935', title: '腐败之神(蚊与蝇)' },
    { id: '[ASDR]-936', title: '' },
    { id: '[ASDR]-937', title: '' },
    { id: '[ASDR]-938', title: '' },
    { id: '[ASDR]-939', title: '' },
    { id: '[ASDR]-940', title: '' },
    { id: '[ASDR]-941', title: '' },
    { id: '[ASDR]-942', title: '' },
    { id: '[ASDR]-943', title: '' },
    { id: '[ASDR]-944', title: '' },
    { id: '[ASDR]-945', title: '' },
    { id: '[ASDR]-946', title: '' },
    { id: '[ASDR]-947', title: '幽灵牧场' },
    { id: '[ASDR]-948', title: '' },
    { id: '[ASDR]-949', title: '' },
    { id: '[ASDR]-950', title: '' },
    { id: '[ASDR]-951', title: '' },
    { id: '[ASDR]-952', title: '' },
    { id: '[ASDR]-953', title: '' },
    { id: '[ASDR]-954', title: '' },
    { id: '[ASDR]-955', title: '' },
    { id: '[ASDR]-956', title: '' },
    { id: '[ASDR]-957', title: '' },
    { id: '[ASDR]-958', title: '' },
    { id: '[ASDR]-959', title: '' },
    { id: '[ASDR]-960', title: '都市传说' },
    { id: '[ASDR]-961', title: '' },
    { id: '[ASDR]-962', title: '' },
    { id: '[ASDR]-963', title: '' },
    { id: '[ASDR]-964', title: '' },
    { id: '[ASDR]-965', title: '' },
    { id: '[ASDR]-966', title: '时间线不可逆性质' },
    { id: '[ASDR]-967', title: '' },
    { id: '[ASDR]-968', title: '' },
    { id: '[ASDR]-969', title: '' },
    { id: '[ASDR]-970', title: '' },
    { id: '[ASDR]-971', title: '' },
    { id: '[ASDR]-972', title: '' },
    { id: '[ASDR]-973', title: '' },
    { id: '[ASDR]-974', title: '' },
    { id: '[ASDR]-975', title: '' },
    { id: '[ASDR]-976', title: '' },
    { id: '[ASDR]-977', title: '' },
    { id: '[ASDR]-978', title: '泛黄的日记本' },
    { id: '[ASDR]-979', title: '' },
    { id: '[ASDR]-980', title: '' },
    { id: '[ASDR]-981', title: '' },
    { id: '[ASDR]-982', title: '' },
    { id: '[ASDR]-983', title: '' },
    { id: '[ASDR]-984', title: '鬼电车' },
    { id: '[ASDR]-985', title: '' },
    { id: '[ASDR]-986', title: '' },
    { id: '[ASDR]-987', title: '' },
    { id: '[ASDR]-988', title: '' },
    { id: '[ASDR]-989', title: '' },
    { id: '[ASDR]-990', title: '' },
    { id: '[ASDR]-991', title: '' },
    { id: '[ASDR]-992', title: '' },
    { id: '[ASDR]-993', title: '' },
    { id: '[ASDR]-994', title: '' },
    { id: '[ASDR]-995', title: '' },
    { id: '[ASDR]-996', title: '' },
    { id: '[ASDR]-997', title: '' },
    { id: '[ASDR]-998', title: '' },
    { id: '[ASDR]-999', title: '邀客名单' }
];

// 动态插入 CSS 样式
const style = document.createElement('style');
style.type = 'text/css';
style.innerHTML = `
   /* From Uiverse.io by cssbuttons-io */ 
  .collapse-button {
 --color: #ad0b0b;
     font-family: inherit;
    display: inline-block;
    // width: 8em;
    // height: 2.6em;
    // line-height: 2.5em;
    // margin: 20px;
    position: relative;
    cursor: pointer;
    overflow: hidden;
    border: 2px solid grey;
    transition: color 0.5s;
    z-index: 1;
    font-size: 17px;
    border-radius: 6px;
    font-weight: 500;
    color: black;
    background: rgb(238, 238, 238);
  }

  .collapse-button:before {
    content: "";
    position: absolute;
    z-index: -1;
    background: var(--color);
    height: 150px;
    width: 200px;
    border-radius: 50%;
  }

  .collapse-button:hover {
    color: #fff;
  }

  .collapse-button:before {
    top: 100%;
    left: 100%;
    transition: all 0.7s;
  }

  .collapse-button:hover:before {
    top: -30px;
    left: -30px;
  }

  .collapse-button:active:before {
    background: #ff8484;
    transition: background 0s;
  }

  /* 修改每个项目的 listItem 样式 */
  .project-item {
    border: 2px solid rgb(238, 238, 238); /* 边框颜色 */
    border-radius: 3px; /* 设置圆角边框 */
    padding: 10px;
    margin: 10px 0;
    font-size: 20px; /* 设置字体大小 */
    color: #333; /* 文字颜色 */
    font-family: '宋体', sans-serif; /* 文字字体 */
    background-color: #f9f9f9; /* 可选：背景色 */
  }

  /* 让项目条目更好看 */
  .project-item span {
    display: block;
    margin-bottom: 5px;
  }
`;

// 将动态创建的样式表添加到 <head>
document.head.appendChild(style);

// 根据当前页生成项目列表
function loadProjects(page) {
    const itemsPerPage = 100; // 每页显示的项目数，示例为100
    const start = page * itemsPerPage;
    const end = start + itemsPerPage;
    const paginatedProjects = projects.slice(start, end);

    const projectList = document.getElementById('project-list');
    projectList.innerHTML = ''; // 清空现有内容

    // 动态创建项目列表
    paginatedProjects.forEach(project => {
        const listItem = document.createElement('li');
        listItem.className = 'project-item';
        listItem.innerHTML = `
            <span>${project.id} - ${project.title}</span>
            <button class="collapse-button">详情</button>
        `;

        // 查找刚生成的按钮并绑定点击事件
        const button = listItem.querySelector('.collapse-button');
        button.addEventListener('click', () => {
            // 跳转到对应的详情页面
            if (project.title) {
                // 假设详情页面 URL 格式为 `/details/<项目ID>.html`
                window.location.href = `/details/${project.id}.html`;
            } else {
                alert('该项目暂无详情页！');
            }
        });

        projectList.appendChild(listItem);
    });
}

// 页面按钮点击事件
document.querySelectorAll('.page-button').forEach(button => {
    button.addEventListener('click', () => {
        const page = parseInt(button.getAttribute('data-page'));
        loadProjects(page);
    });
});

// 默认加载第一页
loadProjects(0);
